repeat task.wait() until game:IsLoaded()
local Wizard = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))()
local Window = Wizard:NewWindow("Area 51")
local Section = Window:NewSection("Portal (Hidden Weapons)")
Section:CreateButton("RGB", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-1367, 1068, 984)
end)
Section:CreateButton("Dual LX3", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(71, 1098, 1948)
end)
Section:CreateButton("LXD", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(2240, 1149, 57)
end)
Section:CreateButton("Corrupted Rifle", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-2104, 948, -432)
end)
local Section = Window:NewSection("Bosses")
Section:CreateButton("Reaper", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-188, 980, 280)
end)
Section:CreateButton("Jack O'Lantern", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-480, 866, -270)
end)
local Section = Window:NewSection("Hidden Weapons")
Section:CreateButton("Safezone", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(61, 1063, 1160)
end)
Section:CreateButton("HEX Spitter", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-584, 1080, 1088)
end)
Section:CreateButton("LXW", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-15, 860, -43)
end)
Section:CreateButton("Ice Crossbow", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(244, 687, 945)
end)
Section:CreateButton("Red Missile Launcher", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-353, 1071, 411)
end)
Section:CreateButton("Vulcan", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-601, 951, 156)
end)
local Section = Window:NewSection("Water Gun")
Section:CreateButton("1 of 3", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-444, 973, -196)
end)
Section:CreateButton("2 of 3", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-282, 973, -92)
end)
Section:CreateButton("3 of 3", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-363, 958, -54)
end)
local Section = Window:NewSection("Burning Sword")
Section:CreateButton("1 of 2", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(-20, 1049, 1159)
end)
Section:CreateButton("2 of 2", function()
game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = CFrame.new(61, 1063, 1160)
end)
